### ISSUE TITLE
Client is not registered. 

### ISSUE THREAD

**Issue by Oremuss** [rtr-nettest/open-rmbt-android#1]
Hey guys,

 I am trying to run this app but I am little bit struggling to do so. I have created all servers on my notebook ( Control, Map and Statistic and also rmbt database in postgresql with secret key ). I made my IP visible from intneret using free tunneling service "ngrok". 

So now I have IP -> xxxx.ngrok.io that refers to my localhost. 
Using  **`xxxx.ngrok.io/RMBTControlServer/version`** I can check version of my server that is running and visible from outside.

Now I would like to run it together with this android app to perform measuremets of LTE and store data to my database located in my "server" on notebook.

I have followed your guide in README.MD and changed everything as follows:
*********************************************************************************************
- CONTROL_SERVER_HOST = **"xxxx.ngrok.io"**
CONTROL_SERVER_CHECK_PRIVATE_IPV4_HOST = **"xxxx.ngrok.io"**
CONTROL_SERVER_CHECK_PRIVATE_IPV6_HOST =  **"" ( empty)**
CONTROL_SERVER_CHECK_PUBLIC_IPV4_URL = **"xxxx.ngrok.io"**
CONTROL_SERVER_CHECK_PUBLIC_IPV6_URL = **"" (empty)**
CONTROL_SERVER_PORT = **"80"**
CONTROL_SERVER_USE_SSL = **"" (empty)**
CONTROL_SERVER_SETTINGS_PATH = **"RMBTControlServer/settings"**
CONTROL_SERVER_TEST_REQUEST_PATH = **"RMBTControlServer/testRequest"**

Now this is really what can you find in my code except that xxxx in ngrok.io domain of course :).  
**I want to ask what am I doing wrong because my app doesnt work.**
********************************************************************************************
 When I press button to start test, it writes down: **`Client is not registred, try again later.`** I guess the connection is somehow wrong and it cannot connect to server or maybe I am doing something wrong. 

Any idea what should I try?

**Comment by alexandersokol** [comment]
Hello, 
Pls build the application and send code that contains in generated rtr.rmbt.android.BuildConfig file.
Also pls paste an error code from logcat while you getting an error.

btw, results not sending to the server in this version yet

**Comment by Oremuss** [comment]
I will do it after I retrun from work (in the evening).  I am "playing" with this in my free time, just to learn new things :)
So if I understood correctly and I want to send results to database I have to use older version of app.

**Comment by alexandersokol** [comment]
Yes, this is currently a prototype of RMBT Android client, and it has WIP status :)
