### ISSUE TITLE
Wrong LTE TAC and CI

### ISSUE THREAD

**Issue by vraida** [rtr-nettest/open-rmbt-android#5]
Hi,

I think that RTR NetTest swaps the TAC and CI identifiers in the case of 4G measurements.
For example, this measurement https://data.netztest.at/opendata/opentests/O31d2b01c-9f6e-4f6f-8077-9071b8b77b3a?verbose=1
shows under speed_curve.signal[0].cell_info_4G the following:
pci = 3, earfcn = 1700, tac = 213771, ci = 17004

This cannot be correct - TAC is only 16 bit; hence smaller or equal to 65535.

I have checked the same cell with a different application, which shows
pci = 3, earfcn = 1700, tac = 17004, cellid = 000213771

Best regards,
Vaclav

**Comment by dzlabing** [comment]
Hi Vaclav,

Thank you for this issue report. The open data output of identifiers is actually swapped on tests done with the new app. The issue will be fixed in https://github.com/rtr-nettest/open-rmbt, this is the code which provides open data.

Best regards,

Dietmar

**Comment by vraida** [comment]
Dear Dietmar, thank you for your quick response.

Will some fix be applied also to the historical database entries queried via the OpenData API?
I mean, it would be inconvenient to address new measurements as
```
tac = cell_info_4G.tac
ci = cell_info_4G.ci
```
and old measurements as
```
tac = cell_info_4G.ci
ci = cell_info_4G.tac
```

Best regards,
Vaclav

**Comment by dzlabing** [comment]
Dear Vaclav,

all should be fixed now.

Best regards,
Dietmar
