### ISSUE TITLE
5G Signal Strength

### ISSUE THREAD

**Issue by vraida** [rtr-nettest/open-rmbt-android#6]
Hi, I noticed that the newer versions of Android RTR-NetTest display 5G signal strength.
Are you going to pass 5G parameters (signal info, cell info) also to the control server and make it accessible via OpenData interface?
Thanks for answer :-)

Best regards,
Vaclav

**Comment by cproof** [comment]
Hi,
we are working on it, but dealing with and sanitizing 5G signal strength data is troublesome due to different manufacturer implementations. Unfortunately we cannot give a timeframe.
Best regards,
Thomas
